### ISSUE TITLE
runtime error: index out of range [5] with length 1

### ISSUE THREAD

**Issue by aborruso** [google/docsy#578]
Hi,
when I run hugo server I have

```
Start building sites …
panic: runtime error: index out of range [5] with length 1

goroutine 114 [running]:
github.com/bep/gitmap.toGitInfo(0xc00020ebd0, 0x66, 0x20669b0, 0x1, 0x0)
        /go/pkg/mod/github.com/bep/gitmap@v1.1.2/gitmap.go:128 +0x3d6
github.com/bep/gitmap.Map(0xc00004a044, 0x31, 0x0, 0x0, 0x31, 0x1, 0x0)
        /go/pkg/mod/github.com/bep/gitmap@v1.1.2/gitmap.go:90 +0x5b3
github.com/gohugoio/hugo/hugolib.newGitInfo(0x23b0a38, 0xc000238a20, 0xd, 0x1, 0xc00007b830)
        /root/project/hugo/hugolib/gitinfo.go:40 +0x6a
github.com/gohugoio/hugo/hugolib.(*HugoSites).loadGitInfo(0xc00025ee40, 0xc0004d25a0, 0xc)
        /root/project/hugo/hugolib/hugo_sites.go:400 +0x8b
github.com/gohugoio/hugo/hugolib.newHugoSites.func4(0x4d1ac8, 0x8, 0x203000, 0x13a8d60)
        /root/project/hugo/hugolib/hugo_sites.go:366 +0x2e
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
        /root/project/hugo/lazy/init.go:97 +0x134
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc0003d5e88, 0xc00007b900)
        /root/project/hugo/lazy/once.go:53 +0xea
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc0003d5e60, 0xc000100000, 0x0, 0x203000, 0x203000)
        /root/project/hugo/lazy/init.go:79 +0x5b
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
        /root/project/hugo/lazy/init.go:102 +0xbd
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc0003d5ca8, 0xc00007b9e8)
        /root/project/hugo/lazy/once.go:53 +0xea
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc0003d5c80, 0x78, 0x1e54aa0, 0x23aa101, 0xc00070a280)
        /root/project/hugo/lazy/init.go:79 +0x5b
github.com/gohugoio/hugo/hugolib.(*HugoSites).gitInfoForPage(0xc00025ee40, 0x23f4040, 0xc00076fc50, 0x0, 0x0, 0x1f422eb)
        /root/project/hugo/hugolib/hugo_sites.go:193 +0x3a
github.com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode(0xc0008f5b60, 0xc0009f4000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:132 +0x37a
github.com/gohugoio/hugo/hugolib.(*pageMap).assembleSections.func1(0x234f178, 0x1, 0x1cba360, 0xc0009f4000, 0x1cdd800)
        /root/project/hugo/hugolib/content_map_page.go:473 +0x235
github.com/armon/go-radix.recursiveWalk(0xc0009f4030, 0xc00056dd90, 0xc00007bd40)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xd7
github.com/armon/go-radix.recursiveWalk(0xc0008fefc0, 0xc00056dd90, 0xa19bf6)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x74
github.com/armon/go-radix.(*Tree).Walk(...)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pageMap).assembleSections(0xc0008f5b60, 0x0, 0xc0008ff020)
        /root/project/hugo/hugolib/content_map_page.go:429 +0x90
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages(0xc0008f5b60, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:324 +0x73
github.com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc0008f5b60, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:711 +0x6c
github.com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:779 +0x2e
github.com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0x0, 0x0)
        /root/project/hugo/common/para/para.go:52 +0x2f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000aaf050, 0xc00047e120)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

These my steps:

- `git clone https://github.com/google/docsy-example.git`
- `cd docsy-example`
- `git submodule update --init --recursive`
-  `hugo server`

I have `hugo v0.83.1-5AFE0A57+extended linux/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio` and `go version go1.13.3 linux/amd64`

**Comment by aborruso** [comment]
Please @LisaFC what can I do to solve it.

I have:

- go version go1.15.8 linux/amd64
- hugo v0.83.1-5AFE0A57+extended linux/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio


I have

```
Start building sites …
panic: runtime error: index out of range [5] with length 1

goroutine 90 [running]:
github.com/bep/gitmap.toGitInfo(0xc0009a2000, 0x66, 0x20669b0, 0x1, 0x0)
        /go/pkg/mod/github.com/bep/gitmap@v1.1.2/gitmap.go:128 +0x3d6
github.com/bep/gitmap.Map(0xc00004a044, 0x31, 0x0, 0x0, 0x31, 0x1, 0x0)
        /go/pkg/mod/github.com/bep/gitmap@v1.1.2/gitmap.go:90 +0x5b3
github.com/gohugoio/hugo/hugolib.newGitInfo(0x23b0a38, 0xc0002b0ea0, 0xd, 0x1, 0x164)
        /root/project/hugo/hugolib/gitinfo.go:40 +0x6a
github.com/gohugoio/hugo/hugolib.(*HugoSites).loadGitInfo(0xc0002d6e40, 0xc000738000, 0x10000000a)
        /root/project/hugo/hugolib/hugo_sites.go:400 +0x8b
github.com/gohugoio/hugo/hugolib.newHugoSites.func4(0x4defd7, 0x8, 0x203000, 0x7f51b0815a88)
        /root/project/hugo/hugolib/hugo_sites.go:366 +0x2e
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
        /root/project/hugo/lazy/init.go:97 +0x134
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc0006fa7a8, 0xc00007b900)
        /root/project/hugo/lazy/once.go:53 +0xea
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc0006fa780, 0xc000100400, 0x0, 0x203000, 0x203000)
        /root/project/hugo/lazy/init.go:79 +0x5b
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
        /root/project/hugo/lazy/init.go:102 +0xbd
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc0006fa5c8, 0xc00007b9e8)
        /root/project/hugo/lazy/once.go:53 +0xea
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc0006fa5a0, 0x78, 0x1e54aa0, 0x23aa101, 0xc000a02080)
        /root/project/hugo/lazy/init.go:79 +0x5b
github.com/gohugoio/hugo/hugolib.(*HugoSites).gitInfoForPage(0xc0002d6e40, 0x23f4040, 0xc00051f6e0, 0x0, 0x0, 0x1f422eb)
        /root/project/hugo/hugolib/hugo_sites.go:193 +0x3a
github.com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode(0xc000843b70, 0xc000518000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:132 +0x37a
github.com/gohugoio/hugo/hugolib.(*pageMap).assembleSections.func1(0x234f178, 0x1, 0x1cba360, 0xc000518000, 0x1cdd800)
        /root/project/hugo/hugolib/content_map_page.go:473 +0x235
github.com/armon/go-radix.recursiveWalk(0xc000518030, 0xc000affd90, 0xc00007bd40)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xd7
github.com/armon/go-radix.recursiveWalk(0xc00084afc0, 0xc000affd90, 0xa19bf6)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x74
github.com/armon/go-radix.(*Tree).Walk(...)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pageMap).assembleSections(0xc000843b70, 0x0, 0xc00084b020)
        /root/project/hugo/hugolib/content_map_page.go:429 +0x90
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages(0xc000843b70, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:324 +0x73
github.com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc000843b70, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:711 +0x6c
github.com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:779 +0x2e
github.com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0x0, 0x0)
        /root/project/hugo/common/para/para.go:52 +0x2f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0004f4b40, 0xc0005fbda0)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:54 +0x66
```

**Comment by LisaFC** [comment]
That's very odd. I'll take a look now.

**Comment by LisaFC** [comment]
Can you try it with a Hugo downgrade (eg 0.75) just to narrow down whether it's to do with this specific recent version of Hugo?

**Comment by aborruso** [comment]
Thank you @LisaFC , using 0.75.1 I have

```
Start building sites …
panic: runtime error: index out of range [5] with length 1

goroutine 116 [running]:
github.com/bep/gitmap.toGitInfo(0xc000b5b8f0, 0x66, 0x20c0563, 0x1, 0x0)
        /go/pkg/mod/github.com/bep/gitmap@v1.1.2/gitmap.go:128 +0x3cf
github.com/bep/gitmap.Map(0xc000046044, 0x31, 0x0, 0x0, 0x31, 0x1, 0x0)
        /go/pkg/mod/github.com/bep/gitmap@v1.1.2/gitmap.go:90 +0x5b3
github.com/gohugoio/hugo/hugolib.newGitInfo(0x25b6720, 0xc00085a3f0, 0xd, 0x1, 0x529)
        /root/project/hugo/hugolib/gitinfo.go:41 +0x6a
github.com/gohugoio/hugo/hugolib.(*HugoSites).loadGitInfo(0xc00015b3f0, 0x206b200, 0xc)
        /root/project/hugo/hugolib/hugo_sites.go:387 +0x8b
github.com/gohugoio/hugo/hugolib.newHugoSites.func4(0x4c9748, 0x203000, 0x203000, 0x203000)
        /root/project/hugo/hugolib/hugo_sites.go:353 +0x2e
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
        /root/project/hugo/lazy/init.go:97 +0x131
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc00007e2c8, 0xc000c5d8f8)
        /root/project/hugo/lazy/once.go:53 +0xea
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc00007e2a0, 0x203000, 0x203000, 0xc000c5d960, 0x4cced8)
        /root/project/hugo/lazy/init.go:79 +0x5b
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
        /root/project/hugo/lazy/init.go:102 +0xbd
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc00050df48, 0xc000c5d9e0)
        /root/project/hugo/lazy/once.go:53 +0xea
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc00050df20, 0x80, 0x1fa2420, 0x25b1301, 0xc00009a200)
        /root/project/hugo/lazy/init.go:79 +0x5b
github.com/gohugoio/hugo/hugolib.(*HugoSites).gitInfoForPage(0xc00015b3f0, 0x25f8f60, 0xc000b5d830, 0x0, 0x0, 0x20c3a31)
        /root/project/hugo/hugolib/hugo_sites.go:179 +0x3a
github.com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode(0xc000937bb0, 0xc000c603f0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:132 +0x37a
github.com/gohugoio/hugo/hugolib.(*pageMap).assembleSections.func1(0x20c0536, 0x1, 0x1dcfe80, 0xc000c603f0, 0x1e04400)
        /root/project/hugo/hugolib/content_map_page.go:475 +0x235
github.com/armon/go-radix.recursiveWalk(0xc000c60420, 0xc000731d90, 0xc000c5dd40)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xd7
github.com/armon/go-radix.recursiveWalk(0xc000cf2450, 0xc000731d90, 0xa26916)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x74
github.com/armon/go-radix.(*Tree).Walk(...)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pageMap).assembleSections(0xc000937bb0, 0x0, 0xc000cf24b0)
        /root/project/hugo/hugolib/content_map_page.go:431 +0x92
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages(0xc000937bb0, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:325 +0x73
github.com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc000937bb0, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:716 +0x69
github.com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:784 +0x2e
github.com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0x0, 0x0)
        /root/project/hugo/common/para/para.go:52 +0x2f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000b5d620, 0xc000c2ab00)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

**Comment by LisaFC** [comment]
Hmm, ok. And can I ask what OS you're running on? The Docsy example site at example.docsy.dev (which is pulled straight from the repo) is running on Netlify with Hugo 0.76 extended, so it's strange that it's not running for you even with a slightly earlier version. We have a known issue for MacOS where it can't handle too many open files, but the error it throws is different.

Also can you just run "hugo" (rather than "hugo server") - will it even build?

**Comment by aborruso** [comment]
> Hmm, ok. And can I ask what OS you're running on? 

Distributor ID: Debian
Description:    Pengwin
Release:        11
Codename:       bullseye

> Also can you just run "hugo" (rather than "hugo server") - will it even build?

```
Start building sites …
panic: runtime error: index out of range [5] with length 1

goroutine 148 [running]:
github.com/bep/gitmap.toGitInfo(0xc000c605b0, 0x66, 0x20c0563, 0x1, 0x0)
        /go/pkg/mod/github.com/bep/gitmap@v1.1.2/gitmap.go:128 +0x3cf
github.com/bep/gitmap.Map(0xc000048044, 0x31, 0x0, 0x0, 0x31, 0x1, 0x0)
        /go/pkg/mod/github.com/bep/gitmap@v1.1.2/gitmap.go:90 +0x5b3
github.com/gohugoio/hugo/hugolib.newGitInfo(0x25b6720, 0xc0005f8480, 0xd, 0x1, 0xc0006a0a2e)
        /root/project/hugo/hugolib/gitinfo.go:41 +0x6a
github.com/gohugoio/hugo/hugolib.(*HugoSites).loadGitInfo(0xc0009d8a50, 0x206b200, 0x8)
        /root/project/hugo/hugolib/hugo_sites.go:387 +0x8b
github.com/gohugoio/hugo/hugolib.newHugoSites.func4(0x40, 0x32008f8, 0xc000cb5818, 0xc000cb5878)
        /root/project/hugo/hugolib/hugo_sites.go:353 +0x2e
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
        /root/project/hugo/lazy/init.go:97 +0x131
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc0005c9528, 0xc000cb58f8)
        /root/project/hugo/lazy/once.go:53 +0xea
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc0005c9500, 0x203000, 0x203000, 0x7f1d7804ab60, 0x0)
        /root/project/hugo/lazy/init.go:79 +0x5b
github.com/gohugoio/hugo/lazy.(*Init).Do.func1()
        /root/project/hugo/lazy/init.go:102 +0xbd
github.com/gohugoio/hugo/lazy.(*onceMore).Do(0xc0005c9348, 0xc000cb59e0)
        /root/project/hugo/lazy/once.go:53 +0xea
github.com/gohugoio/hugo/lazy.(*Init).Do(0xc0005c9320, 0x80, 0x1fa2420, 0x25b1301, 0xc00058c000)
        /root/project/hugo/lazy/init.go:79 +0x5b
github.com/gohugoio/hugo/hugolib.(*HugoSites).gitInfoForPage(0xc0009d8a50, 0x25f8f60, 0xc0008a7560, 0x0, 0x0, 0x20c3a31)
        /root/project/hugo/hugolib/hugo_sites.go:179 +0x3a
github.com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode(0xc000556d10, 0xc000a8e000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:132 +0x37a
github.com/gohugoio/hugo/hugolib.(*pageMap).assembleSections.func1(0x20c0536, 0x1, 0x1dcfe80, 0xc000a8e000, 0x1e04400)
        /root/project/hugo/hugolib/content_map_page.go:475 +0x235
github.com/armon/go-radix.recursiveWalk(0xc000a8e030, 0xc000543d90, 0xc000cb5d40)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xd7
github.com/armon/go-radix.recursiveWalk(0xc000715740, 0xc000543d90, 0xa26916)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x74
github.com/armon/go-radix.(*Tree).Walk(...)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pageMap).assembleSections(0xc000556d10, 0x0, 0xc0007157a0)
        /root/project/hugo/hugolib/content_map_page.go:431 +0x92
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages(0xc000556d10, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:325 +0x73
github.com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc000556d10, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:716 +0x69
github.com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:784 +0x2e
github.com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0x0, 0x0)
        /root/project/hugo/common/para/para.go:52 +0x2f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0008a7350, 0xc000c45a00)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

**Comment by aborruso** [comment]
@LisaFC I have no problem using an hello world hugo website

![Uploading image.png…]()

**Comment by LisaFC** [comment]
I'll keep digging into this but it might be worth posting to the Hugo forums as well - https://discourse.gohugo.io/

**Comment by aborruso** [comment]
> I'll keep digging into this but it might be worth posting to the Hugo forums as well - https://discourse.gohugo.io/

Done https://discourse.gohugo.io/t/runtime-error-index-out-of-range/33321
