### ISSUE TITLE
Cannot find module 'autoprefixer'

### ISSUE THREAD

**Issue by markgoho** [google/docsy#999]
Trying to build docsy locally with `hugo` and cannot get past this step:

``` bash
Start building sites … 
hugo v0.98.0-165d299cde259c8b801abadc6d3405a229e449f6+extended windows/amd64 BuildDate=2022-04-28T10:23:30Z VendorInfo=gohugoio
Error: Error building site: POSTCSS: failed to transform "scss/main.css" (text/css): Error: Loading PostCSS Plugin failed: Cannot find module 'autoprefixer'
Require stack:
- C:\Users\Mark\AppData\Local\Temp\hugo_cache\modules\filecache\modules\pkg\mod\github.com\google\docsy@v0.2.0\postcss.config.js

(@C:\Users\Mark\AppData\Local\Temp\hugo_cache\modules\filecache\modules\pkg\mod\github.com\google\docsy@v0.2.0\postcss.config.js)
    at load (D:\IdeaCrew\GitHub\sbm-docs\node_modules\postcss-load-config\src\plugins.js:28:11)
    at D:\IdeaCrew\GitHub\sbm-docs\node_modules\postcss-load-config\src\plugins.js:53:16
    at Array.map (<anonymous>)
    at plugins (D:\IdeaCrew\GitHub\sbm-docs\node_modules\postcss-load-config\src\plugins.js:52:8)
    at processResult (D:\IdeaCrew\GitHub\sbm-docs\node_modules\postcss-load-config\src\index.js:37:14)
    at D:\IdeaCrew\GitHub\sbm-docs\node_modules\postcss-load-config\src\index.js:151:14
    at async Promise.all (index 0)
```

**Comment by LisaFC** [comment]
Might be useful to have a look at the Docsy user guide in this repo to compare settings? It's not at the project root.

**Comment by chalin** [comment]
It seems like you might need to upgrade your version of Node. For details see,  [Install/Upgrade Node.js](https://www.docsy.dev/docs/get-started/docsy-as-module/installation-prerequisites/#installupgrade-nodejs). Can you give that a try and let us know if that resolved the issue for you?

**Comment by chalin** [comment]
Actually, I'm quite sure that this is a dup of #464 so I'll close this for now, if you still have the problem add a comment here and I'll reopen the issue.
